### ISSUE TITLE
IDA 7 port?

### ISSUE THREAD

**Issue by khang06** [mailwl/IDA_plugin_3ds#1]
Hey, can you port this to IDA 7? I tried porting it myself, but I only got far enough for IDA to complain about segmentation (SEGMENT: Can't find file segmentation)

**Comment by mailwl** [comment]
i don't remember where the sources, but here compiled version for windows (i'll try to find sources later)
[n3ds.zip](https://github.com/mailwl/IDA_plugin_3ds/files/2208441/n3ds.zip)

**Comment by khang06** [comment]
I think the pull request I created should have similar results (works on my system with cxi, haven't tried firm yet)
